extends Node

const SAVE_PATH := "user://scoutcamp_save.cfg"

# Set true by load_game_state(); cleared once the player node is found and teleported.
var _pending_player_restore := false

func _ready() -> void:
	set_process(false)

# ── Public API ────────────────────────────────────────────────────────────────

func has_save() -> bool:
	return FileAccess.file_exists(SAVE_PATH)

func delete_save() -> void:
	if has_save():
		DirAccess.remove_absolute(SAVE_PATH)

func save() -> void:
	var player := get_tree().get_first_node_in_group("player")
	var cfg := ConfigFile.new()

	# GameManager state
	cfg.set_value("game", "current_day",      GameManager.current_day)
	cfg.set_value("game", "fire_lit",         GameManager.fire_lit)
	cfg.set_value("game", "plant_guide_read", GameManager.plant_guide_read)
	cfg.set_value("game", "animal_guide_read",GameManager.animal_guide_read)
	cfg.set_value("game", "pages_found",      GameManager.pages_found)
	cfg.set_value("game", "skills_completed", GameManager.skills_completed)
	cfg.set_value("game", "badges_earned",    GameManager.badges_earned)

	# Player transform
	if player:
		cfg.set_value("player", "pos_x",    player.global_position.x)
		cfg.set_value("player", "pos_y",    player.global_position.y)
		cfg.set_value("player", "pos_z",    player.global_position.z)
		cfg.set_value("player", "rot_y",    player.rotation_degrees.y)

	# Inventory slots (save scene path per slot, empty string for empty slots)
	var inventory := _get_inventory(player)
	if inventory:
		var slot_paths: Array = []
		for slot in inventory.inventory_slots:
			if slot.slot_data and slot.slot_data.item_model_prefab:
				slot_paths.append(slot.slot_data.item_model_prefab.resource_path)
			else:
				slot_paths.append("")
		cfg.set_value("inventory", "slots", slot_paths)

	var err := cfg.save(SAVE_PATH)
	if err != OK:
		push_error("SaveSystem: failed to write save file (error %d)" % err)

func load_game_state() -> void:
	if not has_save():
		return
	var cfg := ConfigFile.new()
	if cfg.load(SAVE_PATH) != OK:
		push_error("SaveSystem: could not read save file")
		return

	# Restore GameManager — reset() was intentionally NOT called before this.
	# scattered_positions is always regenerated by scatterers on world load,
	# so clear it here to avoid the scatterers finding all slots occupied.
	GameManager.scattered_positions.clear()

	GameManager.current_day       = cfg.get_value("game", "current_day",      1)
	GameManager.fire_lit          = cfg.get_value("game", "fire_lit",         false)
	GameManager.plant_guide_read  = cfg.get_value("game", "plant_guide_read", false)
	GameManager.animal_guide_read = cfg.get_value("game", "animal_guide_read",false)
	GameManager.pages_found       = cfg.get_value("game", "pages_found",      0)
	GameManager.badges_earned     = cfg.get_value("game", "badges_earned",    [])

	# Merge saved skills into the current dict so any new keys added later keep defaults
	var saved_skills: Dictionary = cfg.get_value("game", "skills_completed", {})
	for key in saved_skills:
		if GameManager.skills_completed.has(key):
			GameManager.skills_completed[key] = saved_skills[key]

	# Player position is applied in _process() once the world is ready
	_pending_player_restore = true
	set_process(true)

# ── Deferred player restore ───────────────────────────────────────────────────

func _process(_delta: float) -> void:
	if not _pending_player_restore:
		set_process(false)
		return
	var player := get_tree().get_first_node_in_group("player")
	if not player:
		return  # world not ready yet — try again next frame
	_apply_player_transform(player)
	_restore_inventory(player)
	_pending_player_restore = false
	set_process(false)

func _apply_player_transform(player: Node) -> void:
	var cfg := ConfigFile.new()
	if cfg.load(SAVE_PATH) != OK:
		return
	var px: float = cfg.get_value("player", "pos_x", 0.0)
	var py: float = cfg.get_value("player", "pos_y", 0.0)
	var pz: float = cfg.get_value("player", "pos_z", 0.0)
	var ry: float = cfg.get_value("player", "rot_y", 0.0)
	player.global_position     = Vector3(px, py, pz)
	player.rotation_degrees.y  = ry

func _restore_inventory(player: Node) -> void:
	var cfg := ConfigFile.new()
	if cfg.load(SAVE_PATH) != OK:
		return
	var slot_paths: Array = cfg.get_value("inventory", "slots", [])
	if slot_paths.is_empty():
		return
	var inventory := _get_inventory(player)
	if not inventory:
		return
	for i in min(slot_paths.size(), inventory.inventory_slots.size()):
		var path: String = slot_paths[i]
		if path.is_empty():
			continue
		var scene := load(path) as PackedScene
		if not scene:
			push_warning("SaveSystem: could not load item scene: %s" % path)
			continue
		var item_data := _extract_item_data(scene)
		if item_data:
			inventory.inventory_slots[i].fill_slot(item_data)
	inventory.inventory_full = not inventory.has_free_slot()

func _get_inventory(player: Node) -> InventoryController:
	if not player:
		return null
	return player.get_node_or_null("%InventoryController/CanvasLayer/InventoryUI")

func _extract_item_data(scene: PackedScene) -> ItemData:
	var temp := scene.instantiate()
	var item_data := _find_collectable_item_data(temp)
	if item_data:
		item_data.item_model_prefab = scene
	temp.queue_free()
	return item_data

func _find_collectable_item_data(node: Node) -> ItemData:
	for child in node.get_children():
		if child is CollectableInteraction:
			return child.item_data
	for child in node.get_children():
		var result := _find_collectable_item_data(child)
		if result:
			return result
	return null
